version: '3'
services:
  atlas-base:
    build:
      context: .
      dockerfile: Dockerfile.atlas-base
    image: atlas-base
    networks:
      - atlas
    environment:
      - ATLAS_VERSION

networks:
  atlas:
